#!/usr/bin/env bash
set -x 

rhel () {
yum groupinstall -y "Development Tools"
yum install -y zlib-devel openssl-devel libffi-devel wget
cd /usr/src
wget https://python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
tar xf Python-3.7.3.tar.xz
cd Python-3.7.3
./configure --enable-optimizations --with-ensurepip=install
make altinstall
}





ubuntu () {
  apt update -y
  apt install -y \
  wget \
  build-essential \
  libffi-dev \
  libgdbm-dev \
  libc6-dev \
  libssl-dev \
  zlib1g-dev \
  libbz2-dev \
  libreadline-dev \
  libsqlite3-dev \
  libncurses5-dev \
  libncursesw5-dev \
  xz-utils \
  tk-dev
  cd /usr/src
  
  wget https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
  
  tar xf Python-3.7.3.tar.xz
  
  cd Python-3.7.3
  
  ./configure --enable-optimizations --with-ensurepip=install
  
  make altinstall
}

if [[ $(which yum) ]]; then
  rhel
elif [[ $(which apt) ]]; then
  ubuntu
fi
